version: '3.2'
services:
  legacywebshop:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8888:8080"
    networks:
      local_dev_net:
          aliases:
              - legacywebshop

  # product_microservice:
  #   build:
  #     context: ./Microservices/Product_Microservice
  #     dockerfile: ../.././docker/DockerfileProductMicroservice
  #   ports:
  #     - "8889:8081"
  #   networks:
  #     local_dev_net:
  #         aliases:
  #             - productMicroservice

  category_microservice:
    build:
      context: ./Microservices/category
      dockerfile: ../.././docker/DockerfileCategoryMicroservice
    ports:
      - "8889:8081"
    networks:
      local_dev_net:
          aliases:
              - categoryMicroservice

  web-shop-db-image:
    build:
      context: ./
      dockerfile: ./docker/DockerfileMySQL
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3306:3306"
    networks:
        local_dev_net:
            aliases:
                - web-shop-db-image

networks:
  local_dev_net:
    driver: bridge
