version: '3.2'
services:
  legacywebshop:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8888:8080"
    networks:
      local_dev_net:
          aliases:
              - legacywebshop





  web-shop-db-image:
    build:
      context: ./
      dockerfile: ./docker/DockerfileMySQL
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_USER: webshopuser
      MYSQL_DATABASE: webshop
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3306:3306"
    networks:
        local_dev_net:
            aliases:
                - web-shop-db-image

  categoryms:
    build:
      context: ./category/
      dockerfile: ./docker/DockerfileCategory
    ports:
      - "8890:8082"
    networks:
      local_dev_net:
        aliases:
          - categoryms
    depends_on:
      - web-shop-db-image

  productms:
    build:
      context: ./product/
      dockerfile: ./docker/DockerfileProduct
    ports:
      - "8889:8081"
    networks:
      local_dev_net:
        aliases:
          - productms
    depends_on:
      - web-shop-db-image



networks:
  local_dev_net:
    driver: bridge
