###
# Alle Kategorien
# Erwartung: Status 200
GET http://localhost:8890/categories

###
# Eine vorhandene Kategorie
# Erwartung: Status 200
GET http://localhost:8890/categories/1

###
# Eine nicht vorhandene Kategorie
# Erwartung: Status 404 + Validierungsnachricht
GET http://localhost:8890/categories/11111


###
# Kategorie anlegen
# Erwartung: Status 201
#POST http://localhost:8080/categories?name=test1
POST http://localhost:8890/categories
Content-Type: application/json

{ "name" :  "categoryName" }


###
# Kategorie mit leerem Namen anlegen
# Erwartung: Status 412 + Validierungsnachricht
POST http://localhost:8890/categories
Content-Type: application/json
Cache-Control: no-cache

{ "name" :  "" }

###
# Kategorie mit vorhandenem Namen anlegen
# Erwartung: Status 412 + Validierungsnachricht
POST http://localhost:8890/categories
Content-Type: application/json
Cache-Control: no-cache


{ "name" :  "categoryName" }



###
# vorhandene Kategorie löschen
# Erwartung: Status 200
DELETE http://localhost:8890/categories/3

###
# nicht vorhandene Kategorie löschen
# Erwartung: Status 200
DELETE http://localhost:8890/categories/4
