apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  strategy: {}
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: klausb1805/apache:v6
        name: apache
        ports:
        - containerPort: 80
        resources: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: category
  name: category
spec:
  replicas: 3
  selector:
    matchLabels:
      app: category
  strategy: {}
  template:
    metadata:
      labels:
        app: category
    spec:
      containers:
      - image: klausb1805/category:v6
        name: category
        ports:
        - containerPort: 8082
        resources: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  strategy: {}
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - image: klausb1805/product:v7
        name: product
        ports:
        - containerPort: 8081
        resources: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webshop
  name: webshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webshop
  strategy: {}
  template:
    metadata:
      labels:
        app: webshop
    spec:
      containers:
      - image: klausb1805/webshop:latest
        name: webshop
        ports:
        - containerPort: 8080
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: apache
  name: apache-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: apache
  type: LoadBalancer
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: category
  name: categories
spec:
  ports:
  - port: 8890
    protocol: TCP
    targetPort: 8082
  selector:
    app: category
  type: LoadBalancer
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: product
  name: products
spec:
  ports:
  - port: 8889
    protocol: TCP
    targetPort: 8081
  selector:
    app: product
  type: LoadBalancer
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: webshop
  name: webshop-service
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8080
  selector:
    app: webshop
  type: LoadBalancer
status:
  loadBalancer: {}