apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:5.7.9

        ports:
          - name: tpc
            protocol: TCP
            containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      initContainers:
        - name: init
          image: busybox:1.28
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
              secretKeyRef: 
                key: mysqlrootpwd
                name: mysecret
          - name: MYSQL_PASSWORD
            valueFrom: 
              secretKeyRef: 
                key: mysqlpwd
                name: mysecret
          - name: MYSQL_DATABASE
            value: "webshop"
          - name: MYSQL_USER
            value: "webshopuser"
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-volume-claim
      - name: mysql-initdb
        configMap:
          name: mysql-config 