# Request mit http-client.env.json ausführen

###
# Alle Produkte
# Erwartung: Status 200
GET http://{{host}}:{{port}}/products

###
GET http://{{host}}:{{port}}/products?searchMinPrice=30

###
# Ein vorhandenes Produkt
# Erwartung: Status 200
GET http://{{host}}:{{port}}/products/1

###
# Ein nicht vorhandenes Produkt
# Erwartung: Status 404 + Validierungsnachricht
GET http://{{host}}:{{port}}/products/11111


###
# Produkt anlegen
# Erwartung: Status 201
#POST http://localhost:8080/products?name=test1
POST http://{{host}}:{{port}}/products
Content-Type: application/json

{
  "name" :  "Testprodukt",
  "price" : "999.98",
  "details" : "Details",
  "category" : {
    "categoryId" : "2"
  }
}

###
# vorhandenes Produkt löschen
# Erwartung: Status 204
DELETE http://localhost:8081/products/3

###
# nicht vorhandenes Produkt löschen
# Erwartung: Status 204
DELETE http://localhost:8080/products/4
